[tool.black]
line-length = 80

[tool.ruff]
line-length = 80
lint.select = [
    # "E",   # pycodestyle (errors)s
    # "F",   # pyflakes
    # "W",   # pycodestyle (warnings)
    # "I",   # isort (import sorting)
    # "N",   # pep8-naming
    # "UP",  # pyupgrade (modern syntax)
    # "RET", # flake8-return (return statement style)
    # "RUF", # Ruff-specific rules
    # "B",   # flake8-bugbear (bug-prone patterns)
    # "SIM", # flake8-simplify
    # "TID", # flake8-tidy-imports
    "ALL"
]

lint.ignore = [
    "PT",
    "D",
    "S101",
    "S105",
    "FBT",
    "PLR2004",
    # "C901",
]

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "missing-docstring",
    "too-many-instance-attributes",
    "too-many-public-methods",
    "too-many-arguments",
    "too-many-positional-arguments",
    "too-few-public-methods",
    "duplicate-code",
]

[tool.pylint.format]
max-line-length = 80

[tool.mypy]
ignore_missing_imports = true
strict = true

[tool.bandit]
skips = [
    "B101",  # assert used
]
