[tool.black]
line-length = 80

[tool.ruff]
line-length = 80
lint.select = [
    "E",   # pycodestyle (errors)s
    "F",   # pyflakes
    "W",   # pycodestyle (warnings)
    "I",   # isort (import sorting)
    "N",   # pep8-naming
    "UP",  # pyupgrade (modern syntax)
    "RET", # flake8-return (return statement style)
    "RUF", # Ruff-specific rules
    "B",   # flake8-bugbear (bug-prone patterns)
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
]

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "missing-docstring",
    "too-many-instance-attributes",
]

[tool.pylint.format]
max-line-length = 80

[tool.mypy]
ignore_missing_imports = true
