FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install --no-install-recommends -y ncurses-bin && rm -rf /var/lib/apt/lists/*

ENV TERM=xterm-256color

ENV NAME=Player
ENV HOST=host.docker.internal
ENV PORT=54321

CMD ["sh", "-c", "python client.py --name ${NAME} --host ${HOST} --port ${PORT}"]
