FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install --no-install-recommends -y ncurses-bin && rm -rf /var/lib/apt/lists/*

ENV TERM=xterm-256color

ENV PLAYERS=Player
ENV N_AIS=1

CMD ["sh", "-c", "python local.py --players ${PLAYERS} --n-ais ${N_AIS}"]
