name: CI

on: [push, pull_request]

jobs:
  fmt:
    name: Format Check (black)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install black
        run: pip install black

      - name: Run black (check only)
        run: make fmt-ci

  ruff:
    name: Lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff
        run: make ruff

  pylint:
    name: Lint (pylint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint
        run: make pylint

  mypy:
    name: Lint (mypy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install mypy
        run: pip install mypy

      - name: Run mypy
        run: make mypy

  bandit:
    name: Security Check (bandit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install bandit
        run: pip install bandit

      - name: Run bandit
        run: make bandit

  test:
    name: Unit Tests (unittest)
    runs-on: ubuntu-latest
    needs: [fmt, ruff, pylint, mypy, bandit]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unittest
        run: |
          python -m unittest discover -s tests -p "test_*.py"
